[workspace]
members = [
  "rust/common", "rust/utils"
]
exclude = [
  "rust/solana", "rust/evm"
]

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"